[package]
name = "peekable"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/al8n/peekable"
homepage = "https://github.com/al8n/peekable"
documentation = "https://docs.rs/peekable"
description = "Peakable reader and async reader"
license = "MIT or Apache-2.0"
rust-version = "1.56"
keywords = ["peek", "io", "async", "tokio", "futures"]
categories = ["asynchronous", "network-programming", "development-tools"]

[features]
default = []
future = ["futures-util", "pin-project-lite"]
tokio = ["dep:tokio", "pin-project-lite", "bytes"]

[dependencies]
smallvec = { version = "1", optional = true }

futures-util = { version = "=0.3.29", optional = true, features = ["io"] }
pin-project-lite = { version = "0.2", optional = true }

tokio = { version = "1", default-features = false, optional = true, features = ["io-util"] }
bytes = { version = "1", optional = true }


[dev-dependencies]
futures = { version = "0.3", features = ["executor"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["compat"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
